name: flutter_otp_timer
description: Flutter OTP Timer
version: 0.9.4
maintainer: Rishi Banerjee @rshrc
homepage: https://github.com/rshrc/flutter_otp_timer

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

